trigger:
  branches:
    include:
      - task/webapp-deployment

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'tf-service-connection'
  resourceGroup: 'rg-hrms-dev-ind-si'
  frontendApp: 'app-frontend-inm-dev-ind-si'

stages:
  - stage: BuildAndDeployNext
    jobs:
      - job: DeployNext
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'

          - script: |
              cd $(System.DefaultWorkingDirectory)
              npm install --legacy-peer-deps
              npm run build
              npx next export
              cd out
              zip -r ui.zip *
            displayName: 'Build and Zip Nextjs App'

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az webapp deploy --resource-group $(resourceGroup) \
                  --name $(frontendApp) \
                  --src-path $(System.DefaultWorkingDirectory)/out/ui.zip --type zip
            displayName: 'Deploy nextjs UI'